### ISSUE TITLE
Password validation gets triggered when updating user info

### ISSUE THREAD

**Issue by TarekAlQaddy** [Youssefares/egsl-website-api#54]
Updating user info (first name, last name, date of birth) returns password validation error
![image](https://user-images.githubusercontent.com/17699683/58029941-f2d7ae80-7b1d-11e9-82d6-59dfa2dbb222.png)

**Comment by Youssefares** [comment]
I don't think this is a bug. I think we just need to update our seed file. Nice catch!

**Comment by Youssefares** [comment]
Fixed in b227a687d9dd675ad050024ae2ea2f493a745a32. Seedfile updated.
