### ISSUE TITLE
auth/sign_out sometimes returns 422

### ISSUE THREAD

**Issue by TarekAlQaddy** [Youssefares/egsl-website-api#55]
If user is signed in via a provider (fb, google) sign out flow is OK, If the user is registered through our website, sign out `OPTIONS` request is OK but `DELETE` request returns 422
![image](https://user-images.githubusercontent.com/17699683/58030720-4bf41200-7b1f-11e9-80e6-c68b9b4a9afc.png)

**Comment by Youssefares** [comment]
Is the response body empty? If not can you include it? If you could post the entire json object somewhere and include it here, that'd be great.

**Comment by TarekAlQaddy** [comment]
@Youssefares well, there is no response body yes so the prev screenshot is all I can get from the response

**Comment by Youssefares** [comment]
Fixed in b227a687d9dd675ad050024ae2ea2f493a745a32.
